name: Deploy the backend
on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: crazywebdev/mono-backend:${{ github.sha }}

      - name: Verify Pushed Image
        run: docker pull crazywebdev/mono-backend:${{ github.sha }}
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          run: |
            echo "${{ secrets.SSH_KEY }}" &> ~/ssh_key
            chmod 700 /home/runner/ssh_key
            ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@13.239.238.175 -t "docker stop mono-backend && docker run --name mono-backend -d -p 8080:8080 crazywebdev/mono-backend:${{ github.sha }}"