name: Deploy the backend
on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: crazywebdev/mono-backend:${{ github.sha }}

      - name: Verify Pushed Image
        run: docker pull crazywebdev/mono-backend:${{ github.sha }}
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull crazywebdev/mono-backend:${{ github.sha }}
            sudo docker stop mono-backend || true
            sudo docker rm mono-backend || true
            sudo docker run -d --name mono-backend -p 8080:8080 crazywebdev/mono-backend:${{ github.sha }}